default: cpsc2150/MyQueue/QueueApp.java cpsc2150/MyQueue/QueueApp.java.java
	javac cpsc2150/MyQueue/IQueue.java cpsc2150/MyQueue/ListQueue.java cpsc2150/MyQueue/ArrayQueue.java

run: cpsc2150/MyQueue/IQueue.class cpsc2150/MyQueue/ListQueue.class cpsc2150/MyQueue/ArrayQueue.class
	java cpsc2150.MyQueue.IQueue cspc2150.MyQueue.ListQueue cpsc2150.MyQueue.ArrayQueue

