default: cpsc2150/MyQueue/QueueApp.java cpsc2150/MyQueue/QueueApp.java
	javac cpsc2150/MyQueue/IQueue.java cpsc2150/MyQueue/ListQueue.java cpsc2150/MyQueue/ArrayQueue.java

run: cpsc2150/MyQueue/QueueApp.class cpsc2150/MyQueue/ListQueue.class cpsc2150/MyQueue/ArrayQueue.class cpsc2150/MyQueue/IQueue.class 
	java cpsc2150.MyQueue.QueueApp
