default: cpsc2150/banking/MortgageApp.java cpsc2150/banking/IMortgageView.java cpsc2150/banking/IMortgageController.java cpsc2150/banking/IMortgage.java cpsc2150/banking/ICustomer.java cpsc2150/banking/Mortgage.java cpsc2150/banking/Customer.java cpsc2150/banking/MortgageView.java cpsc2150/banking/MortgageController.java
	javac cpsc2150/banking/MortgageApp.java cpsc2150/banking/IMortgageView.java cpsc2150/banking/IMortgageController.java cpsc2150/banking/IMortgage.java cpsc2150/banking/ICustomer.java cpsc2150/banking/Mortgage.java cpsc2150/banking/Customer.java cpsc2150/banking/MortgageView.java cpsc2150/banking/MortgageController.java

run: cpsc2150/banking/MortgageApp.class cpsc2150/banking/IMortgageView.class cpsc2150/banking/IMortgageController.class cpsc2150/banking/IMortgage.class cpsc2150/banking/ICustomer.class cpsc2150/banking/Mortgage.class cpsc2150/banking/Customer.class cpsc2150/banking/MortgageView.class cpsc2150/banking/MortgageController.class
	java cpsc2150.mortgages.MortgageApp

clean: rm cpsc2150/mortgages/*.class cpsc2150.mortgages.MortgageApp