default: cpsc2150/MyQueue/QueueApp.java cpsc2150/MyQueue/ArrayQueue.java cpsc2150/MyQueue/IQueue.java cpsc2150/MyQueue/ListQueue.java cpsc2150/MyQueue/AbsQueue.java cpsc2150/MyQueue/StringQueueApp.java
	javac -Xlint:unchecked cpsc2150/MyQueue/QueueApp.java cpsc2150/MyQueue/ArrayQueue.java cpsc2150/MyQueue/IQueue.java cpsc2150/MyQueue/ListQueue.java cpsc2150/MyQueue/AbsQueue.java cpsc2150/MyQueue/StringQueueApp.java

runInt: cpsc2150/MyQueue/IQueue.class cpsc2150/MyQueue/ListQueue.class cpsc2150/MyQueue/ArrayQueue.class cpsc2150/MyQueue/QueueApp.class cpsc2150/MyQueue/AbsQueue.class
	java cpsc2150/MyQueue/QueueApp

runDouble: cpsc2150/MyQueue/IQueue.class cpsc2150/MyQueue/ListQueue.class cpsc2150/MyQueue/ArrayQueue.class cpsc2150/MyQueue/AbsQueue.class cpsc2150/MyQueue/DoubleQueueApp.class
	cpsc2150/DoubleQueueApp.java

clean: rm cpsc2150/MyQueue/*.class
