default: cpsc2150/mortgages/Mortgage.java cpsc2150/mortgages/IMortgage.java cpsc2150/mortgages/IMortgageController.java cpsc2150/mortgages/IMortgageView.java cpsc2150/mortgages/MortgageView.java cpsc2150/mortgages/MortgageController.java cpsc2150/mortgages/Customer.java cpsc2150/mortgages/ICustomer.java
	javac cpsc2150/mortgages/Mortgage.java cpsc2150/mortgages/IMortgage.java cpsc2150/mortgages/IMortgageController.java cpsc2150/mortgages/IMortgageView.java cpsc2150/mortgages/MortgageView.java cpsc2150/mortgages/MortgageController.java cpsc2150/mortgages/Customer.java cpsc2150/mortgages/ICustomer.java

run: cpsc2150/mortgages/Mortgage.java cpsc2150/mortgages/IMortgage.java cpsc2150/mortgages/IMortgageController.java cpsc2150/mortgages/IMortgageView.java cpsc2150/mortgages/MortgageView.java cpsc2150/mortgages/MortgageController.java cpsc2150/mortgages/Customer.java cpsc2150/mortgages/ICustomer.java
	java cpsc2150/mortgages/MortgageApp

clean: rm cpsc2150/mortgages/*.class
